import Head from "next/head";
import React from "react";

interface IHeader {
  title: string;
  metas?: {
    name: string;
    content: string;
    [key: string]: string;
  }[];
}

const Header = (props: IHeader) => {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      {props.metas?.map((meta: { name: string; content: string }) => {
        const { name, content, ...rest } = meta;
        return <meta name={meta.name} content={meta.content} {...rest} />;
      }) ?? ""}
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Header;
